# Generated by Django 5.1 on 2024-09-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_extended", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSeriesChart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                (
                    "chart_type",
                    models.CharField(
                        choices=[("BAR", "Bar"), ("LINE", "Line")],
                        default="BAR",
                        max_length=55,
                    ),
                ),
                ("stacked", models.BooleanField(default=False)),
                (
                    "default_time_range",
                    models.IntegerField(
                        choices=[
                            (7, "Last 7 days"),
                            (30, "Last 30 days"),
                            (365, "Last 1 year"),
                            (0, "All time"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "default_scale",
                    models.CharField(
                        choices=[
                            ("HOUR", "Hour"),
                            ("DAY", "Day"),
                            ("WEEK", "Week"),
                            ("MONTH", "Month"),
                        ],
                        default="DAY",
                        max_length=45,
                    ),
                ),
                ("app_label", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("time_field", models.CharField(max_length=255)),
                (
                    "aggregate",
                    models.CharField(
                        choices=[
                            ("COUNT", "COUNT"),
                            ("SUM", "SUM"),
                            ("AVG", "AVG"),
                            ("MIN", "MIN"),
                            ("MAX", "MAX"),
                        ],
                        max_length=45,
                    ),
                ),
                ("aggregate_field", models.CharField(default="*", max_length=255)),
                ("aggregate_label", models.CharField(max_length=255)),
                (
                    "split_field",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "filter_field",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "filters",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Filters for query. Example value: status=1&cate=3",
                        max_length=1000,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
